// Investor Tracking & Persistence Service
// Uses localStorage to persist form data and progress across reloads.
// Investor identity comes from URL params (?email=<email>&name=<name>)
// set by n8n when generating the link.
//
// Link format: https://your-domain.com/?email=investor@example.com&name=John+Doe

const FORM_DATA_PREFIX = 'w9_formdata_';
const TRACKING_PREFIX = 'w9_tracking_';

// ───── URL Helpers ─────

export function getInvestorEmailFromUrl(): string | null {
  const params = new URLSearchParams(window.location.search);
  return params.get('email');
}

export function getInvestorNameFromUrl(): string | null {
  const params = new URLSearchParams(window.location.search);
  return params.get('name');
}

/**
 * Check whether the current page load has an investor context
 * (i.e. the URL was generated by n8n with ?email=... params)
 */
export function hasInvestorContext(): boolean {
  return !!getInvestorEmailFromUrl();
}

// ───── Form Data Persistence ─────

export function saveFormData(investorId: string, formData: any): void {
  try {
    localStorage.setItem(FORM_DATA_PREFIX + investorId, JSON.stringify(formData));
  } catch (e) {
    console.warn('Failed to save form data to localStorage:', e);
  }
}

export function loadFormData(investorId: string): any | null {
  try {
    const raw = localStorage.getItem(FORM_DATA_PREFIX + investorId);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function clearFormData(investorId: string): void {
  localStorage.removeItem(FORM_DATA_PREFIX + investorId);
}

// ───── Current Step Persistence ─────

export function saveCurrentStep(investorId: string, step: number): void {
  try {
    localStorage.setItem(TRACKING_PREFIX + investorId + '_step', String(step));
  } catch {}
}

export function loadCurrentStep(investorId: string): number | null {
  const raw = localStorage.getItem(TRACKING_PREFIX + investorId + '_step');
  return raw !== null ? parseInt(raw, 10) : null;
}

// ───── "Already opened" flag ─────
// Prevents sending the form.opened webhook on every refresh

export function hasBeenOpened(investorId: string): boolean {
  return localStorage.getItem(TRACKING_PREFIX + investorId + '_opened') === '1';
}

export function markAsOpened(investorId: string): void {
  localStorage.setItem(TRACKING_PREFIX + investorId + '_opened', '1');
}

// ───── "Already started" flag ─────
// Prevents duplicate form.started webhooks

export function hasBeenStarted(investorId: string): boolean {
  return localStorage.getItem(TRACKING_PREFIX + investorId + '_started') === '1';
}

export function markAsStarted(investorId: string): void {
  localStorage.setItem(TRACKING_PREFIX + investorId + '_started', '1');
}

// ───── "Completed" flag ─────

export function hasBeenCompleted(investorId: string): boolean {
  return localStorage.getItem(TRACKING_PREFIX + investorId + '_completed') === '1';
}

export function markAsCompleted(investorId: string): void {
  localStorage.setItem(TRACKING_PREFIX + investorId + '_completed', '1');
}
